import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogOutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  let res = cookies().get('mode')
  
  return (
    <html lang="en">
      <body className={res!= undefined && res.value == 'dark' ? "dark-mode" : ''}>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          {
            session
              ? <span>{session.user.name} <LogOutBtn /></span>
              : <LoginBtn />
          }
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
